---
- hosts: localhost
  become: false
  gather_facts: false
 
  tasks:
  - name: include secrets
    include_vars: ../secrets.yaml

  - name: add zone
    local_action:
      module: memset_zone
      api_key: "{{ api_key }}"
      state: present
      name: "{{ zone_domain }}"
      ttl: 300
    notify: request DNS reload and poll

  - name: add domain to zone
    local_action:
      module: memset_zone_domain
      api_key: "{{ api_key }}"
      state: present
      domain: "{{ zone_domain }}"
      zone: "{{ zone_domain }}"
    notify: request DNS reload and poll

  - name: create DNS record
    local_action:
      module: memset_zone_record
      api_key: "{{ api_key }}"
      state: present
      zone: "{{ zone_domain }}"
      type: "{{ item.type }}"
      record: "{{ item.record }}"
      data: "{{ item.data }}"
      priority: "{{ item.priority | default(0) }}"
      relative: "{{ item.relative | default(False) }}"
      ttl: "{{ item.ttl | default(0) }}"
    with_items: "{{ dns_records }}"
    notify: request DNS reload and poll
 
  handlers:
  - name: request DNS reload and poll
    local_action:
      module: memset_dns_reload
      api_key: "{{ api_key }}"
      poll: true
