---
- hosts: localhost
  become: false
  # strategy: debug

  tasks:
  - name: include secrets
    include_vars: ../secrets.yaml

  - name: create DNS record
    local_action:
      module: memset_zone_record
      api_key: "{{ api_key }}"
      state: present
      zone: aaaatest
      type: A
      record: mail
      data: 1.2.3.5
      ttl: 300
