- hosts: localhost
  become: false

  tasks:
  - name: include secrets
    include_vars: ../secrets.yaml

  - name: add zone
    local_action:
      module: memset_zone
      api_key: "{{ api_key }}"
      state: present
      name: "{{ zone_domain }}"
      ttl: 300
