---
- hosts: localhost
  become: false
  # strategy: debug

  tasks:
  - name: include secrets
    include_vars: ../secrets.yaml

  - name: create DNS records
    local_action:
      module: memset_zone_record
      api_key: "{{ api_key }}"
      state: present
      zone: "{{ zone_domain }}"
      type: "{{ item.type }}"
      record: "{{ item.record }}"
      data: "{{ item.data }}"
      priority: "{{ item.priority | default(0) }}"
      relative: "{{ item.relative | default(False) }}"
      ttl: "{{ item.ttl | default(0) }}"
    with_items: "{{ dns_records }}"
