---
- hosts: localhost
  become: false
  # strategy: debug

  tasks:
  - name: include secrets
    include_vars: ../secrets.yaml

  - name: delete DNS record
    local_action:
      module: memset_zone_record
      api_key: "{{ api_key }}"
      state: absent
      zone: "{{ zone_domain }}"
      type: "{{ item.type }}"
      record: "{{ item.record }}"
      data: "{{ item.data }}"
    with_items: "{{ dns_records }}"
