---
- hosts: localhost
  become: false
  # strategy: debug

  tasks:
  - name: create DNS record
    local_action:
      module: memset_zone_record
      api_key: dcf089a2896940da9ffefb307ef49ccd
      state: absent
      zone: testymctestyface.com
      type: A
      record: mail
      data: 1.2.3.5
      ttl: 300